NAME: 'resnet50.base.adam'

DATASET:
  VAL_SPLIT: test
  TYPE: 'pedes'
  NAME: 'RAP'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 192

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  TYPE: 'resnet50'

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 64
  MAX_EPOCH: 80
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
  #for resnet
    LR_STEP: [40]
  #for convnext
  # LR_STEP: [5]
    TYPE: 'multistep'
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
